//
//  URL+Extension.swift
//  Browser Prototype
//
//  Created by Marius Malyshev on 11.06.2023.
//

import Foundation

extension URL {
    public var schemeIsValid: Bool {
        guard let scheme = scheme else { return false }
        return permanentURISchemes.contains(scheme.lowercased()) && self.absoluteURL.absoluteString.lowercased() != scheme + ":"
    }
}

private let permanentURISchemes = ["aaa",
                                   "aaas",
                                   "about",
                                   "acap",
                                   "acct",
                                   "cap",
                                   "cid",
                                   "coap",
                                   "coaps",
                                   "crid",
                                   "data",
                                   "dav",
                                   "dict",
                                   "dns",
                                   "dtn",
                                   "example",
                                   "file",
                                   "ftp",
                                   "geo",
                                   "go",
                                   "gopher",
                                   "h323",
                                   "http",
                                   "https",
                                   "iax",
                                   "icap",
                                   "im",
                                   "imap",
                                   "info",
                                   "ipn",
                                   "ipp",
                                   "ipps",
                                   "iris",
                                   "iris.beep",
                                   "iris.lwz",
                                   "iris.xpc",
                                   "iris.xpcs",
                                   "jabber",
                                   "ldap",
                                   "leaptofrogans",
                                   "mailto",
                                   "mid",
                                   "msrp",
                                   "msrps",
                                   "mtqp",
                                   "mupdate",
                                   "news",
                                   "nfs",
                                   "ni",
                                   "nih",
                                   "nntp",
                                   "opaquelocktoken",
                                   "pkcs11",
                                   "pop",
                                   "pres",
                                   "reload",
                                   "rtsp",
                                   "rtsps",
                                   "rtspu",
                                   "service",
                                   "session",
                                   "shttp",
                                   "sieve",
                                   "sip",
                                   "sips",
                                   "sms",
                                   "snmp",
                                   "soap.beep",
                                   "soap.beeps",
                                   "stun",
                                   "stuns",
                                   "tag",
                                   "tel",
                                   "telnet",
                                   "tftp",
                                   "thismessage",
                                   "tip",
                                   "tn3270",
                                   "turn",
                                   "turns",
                                   "tv",
                                   "urn",
                                   "vemmi",
                                   "vnc",
                                   "ws",
                                   "wss",
                                   "xcon",
                                   "xcon-userid",
                                   "xmlrpc.beep",
                                   "xmlrpc.beeps",
                                   "xmpp",
                                   "z39.50r",
                                   "z39.50s"]
